name: ChestRefill
main: falkirks\chestrefill\ChestRefill
version: 2.0
author: Falkirks
api: [1.11.0]
load: POSTWORLD
commands:
 refill:
  permission: chestrefill.capture
  description: Add a new chest
  usage: "[ChestRefill] That command is outdated and has been replaced with /chest, this message will be removed in a future version."
permissions:
 chestrefill:
  default: op
  description: Top level ChestRefill permission
  children:
    chestrefill.command:
      default: op
      description: Use all ChesrRefill commands
