name: ChestRefill
main: ChestRefill\ChestRefill
version: 1.1
author: Falkirks
api: [2.0.0]
load: POSTWORLD
commands:
 refill:
  permission: chestrefill.capture
  description: Add a new chest
  usage: "/refill"
permissions:
 chestrefill:
  default: op
  description: Top level ChestRefill permission
  children:
    chestrefill.command:
      default: op
      description: Use all ChesrRefill commands
