name: ChestRefill
main: ChestRefill\ChestRefill
version: 1.0.1
author: Falk
api: [1.11.0]
load: POSTWORLD
commands:
 refill:
  permission: chestrefill.capture
  description: Add a new chest
  usage: /refill
permissions:
 chestrefill:
  default: op
  description: Top level ChestRefill permission
  children:
    chestrefill.command:
      default: op
      description: Use all ChesrRefill commands
